### ISSUE TITLE
First Error after 1 Week 

### ISSUE THREAD

**Issue by Roughtrade** [wiedemannc/deswappify-auto#1]
First off all , great Solution, Thanks !
After 1 Week as Service i got the following Error:

`Dec  8 08:59:12 Hi10x /usr/local/bin/deswappify_auto.py[1059]: [ERROR] Application triggered possible bug. Please report back the following information so it can be fixed.#012Traceback (most recent call last):#012  File "/usr/local/bin/deswappify_auto.py", line 527, in step#012    self.deswappify_parent()#012  File "/usr/local/bin/deswappify_auto.py", line 359, in deswappify_parent#012    work_done = self.select_new_process()#012  File "/usr/local/bin/deswappify_auto.py", line 317, in select_new_process#012    subprocess.check_call([sys.executable] + sys.argv + ["-n"] + [str(p[1]) for p in pids], timeout=self.spawn_timeout)#012  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call#012    raise CalledProcessError(retcode, cmd)#012subprocess.CalledProcessError: Command '['/usr/bin/python3', '/usr/local/bin/deswappify_auto.py', '-l', '-e', '-j', '8', '-t', '120', '-n', '30334', '20513', '1878', '29100', '1058', '1059', '1830', '9237', '1145', '1834', '1899', '1687', '21401', '1973', '1853', '1656', '1189', '1824', '14692', '2650', '1630', '513', '1882', '1852', '1066', '15054', '2239', '1980', '1884', '2319', '3141', '1897', '14754', '2151', '1', '1029', '2850', '20376', '403', '918', '1215', '1880', '916', '1212', '1143', '29797', '1130', '2059', '2036', '1888', '1890', '1035', '1924']' returned non-zero exit status 1.`

**Comment by Roughtrade** [comment]
but i had to make a small change to the code to get it running. 

in line 469 i changed the following:
o = subprocess.check_output("**LC_ALL=C** free -b", shell=True, universal_newlines=True)

this is due to the german localization i suppose

```
free -b
              Gesamt   belegt    frei        gemns. Puffer/Cache verfügbar
Speicher:  6055682048  1576939520  2278363136   775499776  2200379392  3405602816
Auslagerungsspeicher:  6176788480           0  6176788480

LC_ALL=C free -b
              total        used        free      shared  buff/cache   available
Mem:     6055682048  1575268352  2264158208   791183360  2216255488  3391590400
Swap:    6176788480           0  6176788480
```

**Comment by wiedemannc** [comment]
Thanks for reporting. I fixed your comment about the locale. However, I'm not sure about the root cause of the error from the first message. How are you starting the service (command line parameters)? For me, these parameters are running without any issues for months:

`
deswappify_auto.py -v info -l -e -j 8 -t 120
`

**Comment by Roughtrade** [comment]
The script runs as a service with the same parameters as you suggested. The service is still running. The error is output when I call the status of the service.
`systemctl status deswappify`

**Comment by wiedemannc** [comment]
Ok thanks - so it seems that you get this error sporadically but the service itself doesn't seem to be affected. Let's keep an eye on this and if it gets worse, we should check the root cause.
